spring:
  application:
    name: E2EConsumerTest
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test-group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.learning.e2econsumertest.dto"
        spring.json.value.default.type: "com.learning.e2econsumertest.dto.Customer"
        spring.json.use.type.headers: false
server:
  port: 9292
